Initial Word2Vec backend class
ECE493Group8/word2med-backend pull request #6
Opened 2023-03-20 19:55 UTC by christianjans

Get the functions of the 4 functional requirements working with a test model.

I will provide the model files through our Discord. Just place them in a directory called `trained_models/test/` in the `word2med-backend/` directory, and then run `python3 word2med.py` and it should run the four functions on some test calls (defined in `word2med.py`).

TODO:
- [x] Ensure that the data structures returned by the methods can be put into the backend schema

When this is merged, I believe it should close:
- #1 
- #2 
- #3 
- #7

2023-03-20 21:58 UTC, christianjans commented on schemas.py
I have the response schemas also return the input (i.e. the data in the query schemas). I wasn't sure if this is what we want or need. If not, let me know and I can remove it.

2023-03-21 16:40 UTC, jboileau99 commented on schemas.py
@christianjans I think this is good - contributes to the responses being as useable as possible and they don't have many fields in the first place so one extra field is fine

2023-03-21 16:52 UTC, jboileau99 requested changes
Looks great! Good to merge whenever

2023-03-21 16:52 UTC, jboileau99 commented on word2med.py
> +    """The Word2Med model from a saved Word2Vec Gensim model"""
```suggestion
    """The Word2Med model from a saved Word2Vec Gensim model
    
    Attributes:
        model_path: A string containing a path to the trained model
    """
```

2023-03-21 16:52 UTC, jboileau99 commented on word2med.py
> +    """The Word2Med model from a saved Word2Vec Gensim model"""
following https://google.github.io/styleguide/pyguide.html#384-classes

2023-03-21 17:24 UTC, jboileau99 commented
@christianjans Just two small things - I added an env variable to specify the model path then passed that to the model constructor in the flask app, and ran `make docs` to update the api documentation.

2023-03-21 23:24 UTC, merged